const categoriesMock = [
  { name: "Tecnología", products: 12 },
  { name: "Salud", products: 7 },
  { name: "Educación", products: 5 },
  { name: "Deportes", products: 9 },
  { name: "Arte", products: 4 },
  { name: "Oficina", products: 6 },
  { name: "Hogar", products: 10 },
  { name: "Jardinería", products: 3 },
  { name: "Automotriz", products: 8 },
  { name: "Mascotas", products: 11 },
  { name: "Moda", products: 14 },
  { name: "Belleza", products: 13 },
  { name: "Electrónica", products: 15 },
  { name: "Juguetes", products: 6 },
  { name: "Alimentos", products: 20 },
  { name: "Bebidas", products: 9 },
  { name: "Viajes", products: 2 },
  { name: "Música", products: 5 },
  { name: "Libros", products: 18 },
  { name: "Cine", products: 3 },
  { name: "Videojuegos", products: 16 },
  { name: "Hobbies", products: 7 },
  { name: "Fotografía", products: 4 },
  { name: "Herramientas", products: 8 },
  { name: "Seguridad", products: 2 },
  { name: "Infantil", products: 12 },
  { name: "Decoración", products: 9 },
  { name: "Salud mental", products: 3 },
  { name: "Sostenibilidad", products: 5 },
];


export default categoriesMock;
