const categoriesMock = [
  { id: 1, name: "Tecnología", products: 12, image: "💻" },
  { id: 2, name: "Salud", products: 7, image: "🏥" },
  { id: 3, name: "Educación", products: 5, image: "🎓" },
  { id: 4, name: "Deportes", products: 9, image: "🏅" },
  { id: 5, name: "Arte", products: 4, image: "🎨" },
  { id: 6, name: "Oficina", products: 6, image: "🗂️" },
  { id: 7, name: "Hogar", products: 10, image: "🏠" },
  { id: 8, name: "Jardinería", products: 3, image: "🌿" },
  { id: 9, name: "Automotriz", products: 8, image: "🚗" },
  { id: 10, name: "Mascotas", products: 11, image: "🐾" },
  { id: 11, name: "Moda", products: 14, image: "👗" },
  { id: 12, name: "Belleza", products: 13, image: "💅" },
  { id: 13, name: "Electrónica", products: 15, image: "🔌" },
  { id: 14, name: "Juguetes", products: 6, image: "🧸" },
  { id: 15, name: "Alimentos", products: 20, image: "🍽️" },
  { id: 16, name: "Bebidas", products: 9, image: "🍹" },
  { id: 17, name: "Viajes", products: 2, image: "✈️" },
  { id: 18, name: "Música", products: 5, image: "🎵" },
  { id: 19, name: "Libros", products: 18, image: "📚" },
  { id: 20, name: "Cine", products: 3, image: "🎬" },
  { id: 21, name: "Videojuegos", products: 16, image: "🎮" },
  { id: 22, name: "Hobbies", products: 7, image: "🎯" },
  { id: 23, name: "Fotografía", products: 4, image: "📸" },
  { id: 24, name: "Herramientas", products: 8, image: "🛠️" },
  { id: 25, name: "Seguridad", products: 2, image: "🛡️" },
  { id: 26, name: "Infantil", products: 12, image: "👶" },
  { id: 27, name: "Decoración", products: 9, image: "🪞" },
  { id: 28, name: "Salud mental", products: 3, image: "🧠" },
  { id: 29, name: "Sostenibilidad", products: 5, image: "🌱" },
]


export default categoriesMock;
