openapi: 3.0.3
info:
  title: API de TiendaSol
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Sistema
    description: Endpoints relacionados con el estado y funcionamiento general del sistema.
  - name: Notificaciones
    description: Endpoints para gestionar y consultar notificaciones.
  - name: Productos
    description: Endpoints para la gestión y consulta de productos.
  - name: Pedidos
    description: Endpoints para la gestión y consulta de pedidos.
paths:
  /health:
    get:
      tags:
        - Sistema
      summary: Verificar el estado del sistema
      description: |
        Este endpoint permite comprobar si el sistema está funcionando correctamente. Devuelve un mensaje de confirmación si el backend está activo.
      responses:
        '200':
          description: OK
  /notificaciones:
    get:
      tags:
        - Notificaciones
      summary: Listar notificaciones
      description: |
        Devuelve una lista de todas las notificaciones del sistema. 
        Permite filtrar por usuario y por estado de lectura.
      parameters:
        - in: query
          name: userId
          schema:
            type: integer
          description: ID del usuario para filtrar las notificaciones.
        - in: query
          name: leida
          schema:
            type: boolean
          description: Filtrar notificaciones leídas (true) o no leídas (false).
      responses:
        '200':
          description: Lista de notificaciones.
          content:
            application/json:
              schema:
                type: object
                properties:
                  notificaciones:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notificacion'
        '400':
          description: Error de validación en los parámetros.
        '500':
          description: Error interno del servidor.

    post:
      tags:
        - Notificaciones
      summary: Crear una notificación
      description: |
        Crea una nueva notificación basada en un pedido existente. 
        Se debe enviar el ID del pedido.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pedidoId:
                  type: integer
                  description: ID del pedido para generar la notificación.
                  example: 123
              required:
                - pedidoId
      responses:
        '201':
          description: Notificación creada exitosamente.
        '400':
          description: Error en los datos enviados (pedido no existe o inválido).
        '500':
          description: Error interno del servidor.

  /notificaciones/{id}/leida:
   patch:
     tags:
       - Notificaciones
     summary: Marcar notificación como leída
     description: |
       Cambia el estado de la notificación especificada a "leída".
     parameters:
       - in: path
         name: id
         schema:
           type: integer
         required: true
         description: ID de la notificación a actualizar.
     responses:
       '200':
         description: Notificación marcada como leída correctamente.
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: "Notificación marcada como leída"
                 notificacion:
                   $ref: '#/components/schemas/Notificacion'
       '400':
         description: ID inválido.
       '404':
         description: Notificación no encontrada.
       '500':
         description: Error interno del servidor.
  /productos:
    post:
      tags:
        - Productos
      summary: Crear un producto
      description: |
        Permite crear un nuevo producto enviando los datos necesarios en el cuerpo de la solicitud. El producto debe tener un vendedor válido, un título y puede incluir descripción, categorías, precio, moneda, stock, fotos y estado activo.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vendedor:
                  type: integer
                  description: ID del usuario vendedor (debe existir en el sistema).
                  example: 1
                titulo:
                  type: string
                  description: Título del producto (mínimo 3, máximo 50 caracteres).
                  example: "Zapatillas deportivas"
                descripcion:
                  type: string
                  description: Descripción del producto (máximo 500 caracteres).
                  example: "Zapatillas cómodas para correr"
                categorias:
                  type: array
                  items:
                    type: string
                  description: Lista de categorías del producto.
                  example: ["Deportes", "Calzado"]
                precio:
                  type: number
                  description: Precio del producto (debe ser mayor o igual a 0).
                  example: 15000
                moneda:
                  type: string
                  description: >-
                    Moneda del precio. Valores posibles: PESO_ARG, DOLAR_USA, REAL.
                  example: "PESO_ARG"
                stock:
                  type: integer
                  description: Cantidad de stock disponible.
                  example: 10
                fotos:
                  type: array
                  items:
                    type: string
                  description: URLs de fotos del producto.
                  example: ["https://ejemplo.com/foto1.jpg"]
                activo:
                  type: boolean
                  description: Indica si el producto está activo o no.
                  example: true
            required:
              - vendedor
              - titulo
      responses:
        '201':
          description: Producto creado exitosamente.
        '400':
          description: Error en los datos enviados (por ejemplo, campos requeridos faltantes o inválidos).
    get:
      tags:
        - Productos
      summary: Listar productos
      description: |
        Devuelve una lista de todos los productos registrados en el sistema. Permite paginación y filtrado por parámetros opcionales.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Número de página para la paginación.
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Cantidad máxima de productos por página.
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar productos por una busqueda de texto.
        - in: query
          name: maxPrice
          schema:
            type: integer
          description: Filtrar productos por debajo de un precio.
        - in: query
          name: minPrice
          schema:
            type: integer
          description: Filtrar productos por encima de un precio.
      responses:
        '200':
          description: Lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '204':
          description: No se encontraron productos.
  /productos/{id}:
    get:
      tags:
        - Productos
      summary: Obtener producto por ID
      description: Devuelve la información de un producto específico según su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del producto a buscar.
      responses:
        '200':
          description: Producto encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado.
    delete:
      tags:
        - Productos
      summary: Eliminar producto por ID
      description: Elimina un producto específico según su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del producto a eliminar.
      responses:
        '204':
          description: Producto eliminado exitosamente.
        '404':
          description: Producto no encontrado.
    patch:
        tags:
          - Productos
        summary: Actualiza parcialmente un producto existente
        description: Permite modificar uno o más campos de un producto por su ID.
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del producto a actualizar
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: Campos a modificar del producto
        responses:
          '200':
            description: Producto actualizado correctamente
          '400':
            description: Datos inválidos
          '404':
            description: Producto no encontrado
  /productos/vendedor/{id}:
    get:
      tags:
        - Productos
      summary: Listar productos por vendedor
      description: |
        Devuelve una lista de productos asociados a un vendedor específico, identificado por su ID. Permite paginación y filtrado adicional.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del vendedor.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Número de página para la paginación (opcional).
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Cantidad máxima de productos por página (opcional).
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar productos por una busqueda de texto.
        - in: query
          name: maxPrice
          schema:
            type: integer
          description: Filtrar productos por debajo de un precio.
        - in: query
          name: minPrice
          schema:
            type: integer
          description: Filtrar productos por encima de un precio.
      responses:
        '200':
          description: Lista de productos del vendedor.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '204':
          description: No se encontraron productos para el vendedor.

  # --- Pedidos ---
  /pedidos:
    post:
      tags:
        - Pedidos
      summary: Crear un pedido
      description: Crea un nuevo pedido con los datos enviados en el cuerpo de la solicitud.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Datos necesarios para crear un pedido
      responses:
        '201':
          description: Pedido creado exitosamente.
        '400':
          description: Error en los datos enviados.
        '500':
          description: Error interno del servidor.

  /pedidos/{id}/cancelacion:
    post:
      tags:
        - Pedidos
      summary: Cancelar un pedido
      description: Cancela el pedido identificado por el ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del pedido a cancelar.
      responses:
        '200':
          description: Pedido cancelado exitosamente.
        '400':
          description: ID inválido o no se puede cancelar el pedido.
        '404':
          description: Pedido no encontrado.
        '500':
          description: Error interno del servidor.

  /pedidos/usuarios/{id}:
    get:
      tags:
        - Pedidos
      summary: Obtener historial de pedidos de un usuario
      description: Devuelve el historial de pedidos de un usuario específico.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del usuario.
      responses:
        '200':
          description: Historial de pedidos del usuario.
        '404':
          description: Usuario no encontrado o sin pedidos.
        '500':
          description: Error interno del servidor.

  /pedidos/{id}/envio:
    post:
      tags:
        - Pedidos
      summary: Marcar pedido como enviado
      description: Marca el pedido identificado por el ID como enviado.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del pedido a marcar como enviado.
      responses:
        '200':
          description: Pedido marcado como enviado correctamente.
        '400':
          description: ID inválido o no se puede marcar como enviado.
        '404':
          description: Pedido no encontrado.
        '500':
          description: Error interno del servidor.
    /pedidos:
      post:
        tags:
          - Pedidos
        summary: Crear un pedido
        description: Crea un nuevo pedido con los datos enviados en el cuerpo de la solicitud.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: Datos necesarios para crear un pedido
        responses:
          '201':
            description: Pedido creado exitosamente.
          '400':
            description: Error en los datos enviados.
          '500':
            description: Error interno del servidor.

    /pedidos/{id}/cancelacion:
      post:
        tags:
          - Pedidos
        summary: Cancelar un pedido
        description: Cancela el pedido identificado por el ID.
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del pedido a cancelar.
        responses:
          '200':
            description: Pedido cancelado exitosamente.
          '400':
            description: ID inválido o no se puede cancelar el pedido.
          '404':
            description: Pedido no encontrado.
          '500':
            description: Error interno del servidor.

    /pedidos/usuarios/{id}:
      get:
        tags:
          - Pedidos
        summary: Obtener historial de pedidos de un usuario
        description: Devuelve el historial de pedidos de un usuario específico.
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del usuario.
        responses:
          '200':
            description: Historial de pedidos del usuario.
          '404':
            description: Usuario no encontrado o sin pedidos.
          '500':
            description: Error interno del servidor.

    /pedidos/{id}/envio:
      post:
        tags:
          - Pedidos
        summary: Marcar pedido como enviado
        description: Marca el pedido identificado por el ID como enviado.
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del pedido a marcar como enviado.
        responses:
          '200':
            description: Pedido marcado como enviado correctamente.
          '400':
            description: ID inválido o no se puede marcar como enviado.
          '404':
            description: Pedido no encontrado.
          '500':
            description: Error interno del servidor.
components:
  schemas:
    Notificacion:
        type: object
        properties:
          id:
            type: integer
          usuarioDestino:
            type: object
            properties:
              id:
                type: integer
              nombre:
                type: string
              email:
                type: string
              telefono:
                type: integer
              tipo:
                type: string
              fechaAlta:
                type: string
                format: date-time
          mensaje:
            type: string
          leida:
            type: boolean
          fechaAlta:
            type: string
            format: date-time
          fechaLeida:
            type: string
            format: date-time
    Producto:
      type: object
      properties:
        id:
          type: integer
          description: ID único del producto.
          example: 123
        vendedor:
          type: integer
          description: ID del usuario vendedor.
          example: 1
        titulo:
          type: string
          description: Título del producto.
          example: "Zapatillas deportivas"
        descripcion:
          type: string
          description: Descripción del producto.
          example: "Zapatillas cómodas para correr"
        categorias:
          type: array
          items:
            type: string
          description: Lista de categorías del producto.
          example:
            - Deportes
            - Calzado
        precio:
          type: number
          description: Precio del producto.
          example: 15000
        moneda:
          type: string
          description: "Moneda del precio. Valores posibles: PESO_ARG, DOLAR_USA, REAL."
          example: "PESO_ARG"
        stock:
          type: integer
          description: Cantidad de stock disponible.
          example: 10
        fotos:
          type: array
          items:
            type: string
          description: URLs de fotos del producto.
          example:
            - https://ejemplo.com/foto1.jpg
        activo:
          type: boolean
          description: Indica si el producto está activo o no.
          example: true
