openapi: 3.0.3
info:
  title: API de TiendaSol
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Sistema
    description: Endpoints relacionados con el estado y funcionamiento general del sistema.
  - name: Notificaciones
    description: Endpoints para gestionar y consultar notificaciones.
  - name: Productos
    description: Endpoints para la gestión y consulta de productos.
paths:
  /health:
    get:
      tags:
        - Sistema
      summary: Verificar el estado del sistema
      description: |
        Este endpoint permite comprobar si el sistema está funcionando correctamente. Devuelve un mensaje de confirmación si el backend está activo.
      responses:
        '200':
          description: OK
  /notificaciones:
    get:
      tags:
        - Notificaciones
      summary: Obtener notificaciones
      description: |
        Devuelve una lista de notificaciones. Se puede filtrar por el parámetro `leida` para obtener solo las notificaciones leídas o no leídas.
      parameters:
        - in: query
          name: leida
          schema:
            type: boolean
          description: Filtrar por notificaciones leídas o no leídas.
      responses:
        '200':
          description: Lista de notificaciones.
  /notificaciones{id}:
    get:
      tags:
        - Notificaciones
      summary: Obtener una notificación por ID
      description: |
        Devuelve la información de una notificación específica según su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de la notificación a buscar.
      responses:
        '200':
          description: Notificación encontrada.
        '404':
          description: Notificación no encontrada.
  /productos:
    post:
      tags:
        - Productos
      summary: Crear un producto
      description: |
        Permite crear un nuevo producto enviando los datos necesarios en el cuerpo de la solicitud. El producto debe tener un vendedor válido, un título y puede incluir descripción, categorías, precio, moneda, stock, fotos y estado activo.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vendedor:
                  type: integer
                  description: ID del usuario vendedor (debe existir en el sistema).
                  example: 1
                titulo:
                  type: string
                  description: Título del producto (mínimo 3, máximo 50 caracteres).
                  example: "Zapatillas deportivas"
                descripcion:
                  type: string
                  description: Descripción del producto (máximo 500 caracteres).
                  example: "Zapatillas cómodas para correr"
                categorias:
                  type: array
                  items:
                    type: string
                  description: Lista de categorías del producto.
                  example: ["Deportes", "Calzado"]
                precio:
                  type: number
                  description: Precio del producto (debe ser mayor o igual a 0).
                  example: 15000
                moneda:
                  type: string
                  description: >-
                    Moneda del precio. Valores posibles: PESO_ARG, DOLAR_USA, REAL.
                  example: "PESO_ARG"
                stock:
                  type: integer
                  description: Cantidad de stock disponible.
                  example: 10
                fotos:
                  type: array
                  items:
                    type: string
                  description: URLs de fotos del producto.
                  example: ["https://ejemplo.com/foto1.jpg"]
                activo:
                  type: boolean
                  description: Indica si el producto está activo o no.
                  example: true
            required:
              - vendedor
              - titulo
      responses:
        '201':
          description: Producto creado exitosamente.
        '400':
          description: Error en los datos enviados (por ejemplo, campos requeridos faltantes o inválidos).
    get:
      tags:
        - Productos
      summary: Listar productos
      description: |
        Devuelve una lista de todos los productos registrados en el sistema. Permite paginación y filtrado por parámetros opcionales.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Número de página para la paginación.
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Cantidad máxima de productos por página.
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar productos por una busqueda de texto.
        - in: query
          name: maxPrice
          schema:
            type: integer
          description: Filtrar productos por debajo de un precio.
        - in: query
          name: minPrice
          schema:
            type: integer
          description: Filtrar productos por encima de un precio.
      responses:
        '200':
          description: Lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '204':
          description: No se encontraron productos.
  /productos/{id}:
    get:
      tags:
        - Productos
      summary: Obtener producto por ID
      description: Devuelve la información de un producto específico según su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del producto a buscar.
      responses:
        '200':
          description: Producto encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado.
    delete:
      tags:
        - Productos
      summary: Eliminar producto por ID
      description: Elimina un producto específico según su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del producto a eliminar.
      responses:
        '204':
          description: Producto eliminado exitosamente.
        '404':
          description: Producto no encontrado.
    patch:
        tags:
          - Productos
        summary: Actualiza parcialmente un producto existente
        description: Permite modificar uno o más campos de un producto por su ID.
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del producto a actualizar
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: Campos a modificar del producto
        responses:
          '200':
            description: Producto actualizado correctamente
          '400':
            description: Datos inválidos
          '404':
            description: Producto no encontrado
  /productos/vendedor/{id}:
    get:
      tags:
        - Productos
      summary: Listar productos por vendedor
      description: |
        Devuelve una lista de productos asociados a un vendedor específico, identificado por su ID. Permite paginación y filtrado adicional.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del vendedor.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Número de página para la paginación (opcional).
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Cantidad máxima de productos por página (opcional).
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar productos por una busqueda de texto.
        - in: query
          name: maxPrice
          schema:
            type: integer
          description: Filtrar productos por debajo de un precio.
        - in: query
          name: minPrice
          schema:
            type: integer
          description: Filtrar productos por encima de un precio.
      responses:
        '200':
          description: Lista de productos del vendedor.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '204':
          description: No se encontraron productos para el vendedor.
components:
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
          description: ID único del producto.
          example: 123
        vendedor:
          type: integer
          description: ID del usuario vendedor.
          example: 1
        titulo:
          type: string
          description: Título del producto.
          example: "Zapatillas deportivas"
        descripcion:
          type: string
          description: Descripción del producto.
          example: "Zapatillas cómodas para correr"
        categorias:
          type: array
          items:
            type: string
          description: Lista de categorías del producto.
          example:
            - Deportes
            - Calzado
        precio:
          type: number
          description: Precio del producto.
          example: 15000
        moneda:
          type: string
          description: "Moneda del precio. Valores posibles: PESO_ARG, DOLAR_USA, REAL."
          example: "PESO_ARG"
        stock:
          type: integer
          description: Cantidad de stock disponible.
          example: 10
        fotos:
          type: array
          items:
            type: string
          description: URLs de fotos del producto.
          example:
            - https://ejemplo.com/foto1.jpg
        activo:
          type: boolean
          description: Indica si el producto está activo o no.
          example: true
